### ISSUE TITLE
Doubt regarding " Ancient Foreign Communications"

### ISSUE THREAD

**Issue by d4rkvaibhav** [shiltemann/CTF-writeups-public#4]
Can you please tell me that when you got the unicode symbols what was your algorithm to convert it into the normal text using pigpen cipher and t9. In the write up i was not able to understand that part.

**Comment by shiltemann** [comment]
Hi @d4rkvaibhav :) 

sure! ok, the first three letters are encoded as: 

`⨅]]⌞⌞`

look at the top-left image of the pigpen cipher below, in that cipher, `⨅` would mean `H`. Now instead, combine this with T9, it would mean the letter `t` (one press on the number `8`)

Then we have `]]` which would be the `dd` in classic pigpen, but here it signifies 2 presses on the number `4`, which would be an `h`, then  `⌞⌞` is two presses on the 3, so a letter `e`, etc

Does this make it more clear? I will update my writeup to make this more clear

![](https://raw.githubusercontent.com/shiltemann/CTF-writeups-public/master/IceCTF-2018/writeupfiles/pigpen.png)

![](https://raw.githubusercontent.com/shiltemann/CTF-writeups-public/master/IceCTF-2018/writeupfiles/T9.jpeg)

**Comment by d4rkvaibhav** [comment]
@shiltemann Thanks for the explanation. The above explanation has cleared my all doubts.
