### ISSUE TITLE
Artisinal Handcrafted HTTP 3

### ISSUE THREAD

**Issue by d4rkvaibhav** [shiltemann/CTF-writeups-public#5]
Can you please explain a liitle bit more about "Artisinal Handcrafted HTTP 3" that how are you proceeding.Is the code (the GET and Post ) is directly copied paste to the terminal after connecting to the service?

**Comment by hexylena** [comment]
I can write some more details later, but, essentially yes. The service responds with a blank line (and no prompt), and then you just paste the code in. If it's a GET request, then after the first blank line the request is sent and a response is printed. For a POST request when you specify the Content-length header, the blank terminal-like prompt will consume the Headers + a blank line + up to that many characters before sending the data. Does that answer your question?
