### ISSUE TITLE
DareYourMind.net is a porn site

### ISSUE THREAD

**Issue by stcalica** [shiltemann/CTF-writeups-public#7]
I was trying to read your CTF write ups and one of your links leads to porn ....

**Comment by hexylena** [comment]
Oh gosh, sorry about that. It didn't used to be! But looks like it's under new ownership. We'll remove that link.

**Comment by stcalica** [comment]
do you know what happened to the organization you meant?

**Comment by shiltemann** [comment]
here is the entry for it in wechall with a bit of information: https://www.wechall.net/site/details/11/DareYourMind

I don't know what happened, the project was probably just abandoned?
